# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f3a0ec04c4cfe5138e06bf4e9580f972480896872cfe5a0037ce677e626bbcc3408c979c911008fafbbf2d5a7cf68a396e3269919b2ebba4ae290de48df35c0

test:
  secret_key_base: 4583a605dd08b787222368bd48cc57b6748bb7b29a1e851bff1813c417c313a5af8b010d14293ca02d912a78ca311b11db528eb3c3f2673fcc17b2b2b6a79ed0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
